### ISSUE TITLE
Creating a collaboration doesn't accept groups

### ISSUE THREAD

**Issue by michaelhays** [box/box-typescript-sdk-gen#36]
### Description of the Issue

[Creating a collaboration](https://github.com/box/box-typescript-sdk-gen/blob/main/docs/userCollaborations.md#create-collaboration) claims to work for groups, but actually doesn't.

The relevant type [`CreateCollaborationRequestBodyArgAccessibleByFieldTypeField`](https://github.com/box/box-typescript-sdk-gen/blob/c92ae503f40020ee782a12c91ad3e4e78be5554c/src/managers/userCollaborations.generated.ts#L72) accepts `group`, which implies that this usage should work.

### Steps to Reproduce

Run the following code:

```ts
boxClient.userCollaborations.createCollaboration({
  accessibleBy: { type: 'group', id: groupId },
  item: { type: 'folder', id: folderId },
  role: groupRole,
})
```

Box responds with the error: `Invalid value: group`.

### Expected Behavior

The group collaboration is created successfully.

### Versions Used

Typescript SDK: v0.1.2
Platform: Node.js
Node.js: 18.17.1

**Comment by arjankowski** [comment]
Hi @michaelhays, thank you for the issue!

It turns out that we have incorrectly defined the `Collaboration` type in the Box Open API. 
Currently, its field, `accessibleBy`, only allows the `User` type, when in fact the `Group` type should also be possible.

We are currently working on a fix for this and will let you know as soon as we have resolved it.

As for your second question, the collaboration management manager will remain the same as it is now and will still be named `userCollaborations`.

Regards,
Artur

**Comment by michaelhays** [comment]
Thanks for the quick response! Looking forward to it :)

**Comment by arjankowski** [comment]
Hi @michaelhays, 

The new release `v0.1.3` includes a fix for the issue you reported!

Additionally, this version also changes the naming of several core classes (client and authentication) by adding the prefix `Box`. For example, `Client` is now `BoxClient` and `JWAuth` is now `BoxJwtAuth`.

I hope these changes will make it easier to use this SDK.

Thank you once again for reporting the bug.

Best regards,
Artur

**Comment by michaelhays** [comment]
Just upgraded, can confirm that it's working now! Appreciate the update :pray:
