### ISSUE TITLE
Could not integrate typescript-sdk using Oauth 2.0 authentication

### ISSUE THREAD

**Issue by dipenchand** [box/box-typescript-sdk-gen#368]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I'm integrating [box-typescript-sdk-gen](https://github.com/box/box-typescript-sdk-gen) into my Vue3 + Typescript application. But, I couldn't initialize `BoxClient`.

### Steps to Reproduce
I've following code:

```typescript
const redirectUri = window.location.origin + "/#/callback"

const authenticate = async (): Promise<void> => {

const config = new OAuthConfig({
  clientId: <CLIENT_ID>,
  clientSecret: "<CLIENT_SECRET>"
})

const oauth = new BoxOAuth({ config })

if (oauth) {
  const authorizeUrl = oauth.getAuthorizeUrl({
    redirectUri: redirectUri,
    responseType: "code",
    clientId:<CLIENT_ID>,
  })
  
  const authWindow = window.open(authorizeUrl, "_blank", options)
  const authCode = authWindow.location.href.replace(authWindow.location.hash, "").split("code=")[1]
  
  const token = (await oauth?.getTokensAuthorizationCodeGrant(authCode))?.accessToken

  const client = await new BoxClient({
    auth: {
      token: token
    }
  })
  console.log(await client.users.getUserMe())
}
```
I can get **authCode**, **authorizeUrl** and **accessToken** as well. But there is something wrong while using token with BoxClient 

Above implementation throws the following error:
```error
Authentication failed TypeError: options.auth.retrieveAuthorizationHeader is not a function
    at box-typescript-sdk-gen.js?t=1727454723524&v=998a6ba9:8932:47
    at Generator.next (<anonymous>)
    at fulfilled (box-typescript-sdk-gen.js?t=1727454723524&v=998a6ba9:8846:28)
```
### Expected Behavior
When I use `BoxDeveloperTokenAuth`, then it works perfectly, but throws error in the case of Oauth 2.0 authentication.
```typescript
let auth = new BoxDeveloperTokenAuth({
  token: value.target.value,
});
let boxClient = new BoxClient({ auth });
 console.log(client.users.getUserMe())
```

### Screenshots
![image](https://github.com/user-attachments/assets/614b3d29-2a4c-494e-998b-b5f7aef549a5)

### Versions Used
TypeScript: 5.4.2
box-typescript-sdk-gen: ^1.6.0
Platform: Vue3 + TypeScript (Browser)
Node.js (if applicable): 20.10.0

[sdk-docs]: https://github.com/box/box-typescript-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-typescript-sdk-gen/search?type=Issues

**Comment by arjankowski** [comment]
Hello @dipenchand,
Thank you for using our new box-typescript-sdk!

The issue you're encountering occurs due to an incorrect configuration of the `BoxClient`.
The `BoxClient` requires a class that conforms to the `Authentication` interface, as it contains methods used for authentication. However, in your example, you're directly passing a token:
```
 const client = await new BoxClient({
    auth: {
      token: token
    }
  })
 ```
 
 
But to make your code work, you need to pass an instance of the `BoxDeveloperTokenAuth` class to the `BoxClient`:
 ```
   const client = await new BoxClient({
    auth: new BoxDeveloperTokenAuth({ token })
  })
  ```
  
But actually, after successful authorization and obtaining the token, you can use the existing instance of the `BoxOAuth` class to populate the `BoxClient`:

```
 const client = await new BoxClient({
    auth: oauth
  })
```

Let us know if this solved your problem

Regards,
Artur

**Comment by gamenic-dipendra** [comment]
@arjankowski
Thank for your response!

I’m currently using `box-typescript-sdk-gen` on the client side. To keep my Client_Secret secure and avoid exposing it, I’ve generated an AccessToken on the backend (PHP) using an authorization_code.

I was able to make it work like this:
```typescript
oauth = new BoxOAuth({
  config: new OAuthConfig({
    clientId: <Client_ID>,
    clientSecret: ""
  })
})
if (token) {
  oauth.config.tokenStorage.store(token)
  oauth.config.tokenStorage.get()
}

const client = await new BoxClient({
  auth: oauth
})
```

but I was wondering if there's a more efficient way to accomplish the same?

**Comment by arjankowski** [comment]
@gamenic-dipendra,
The example with `BoxDeveloperTokenAuth` I provided was to point out the issue you had in your code, where you were passing the token directly instead of Auth to BoxClient. `BoxDeveloperTokenAuth` should only be used for testing purposes, as unlike other authentication methods, it is not automatically refreshed when it expires.

I recommend reading [this documentation](https://github.com/box/box-typescript-sdk-gen/blob/main/docs/authentication.md), where we explain the available authentication methods and how to use them.

As for your first question, your approach of involving the backend to hide the secret seems correct, and at the moment, I am unable to propose an alternative solution.

Regards,
Artur
