### ISSUE TITLE
TLS error with `box-typescript-sdk-gen` 0.1.8

### ISSUE THREAD

**Issue by michaelhays** [box/box-typescript-sdk-gen#46]
### Description of the Issue

I upgraded to `box-typescript-sdk-gen` 0.1.8 and am running the following code:

```ts
import { BoxClient } from 'box-typescript-sdk-gen/lib/client.generated'
import { BoxJwtAuth, JwtConfig } from 'box-typescript-sdk-gen/lib/jwtAuth'
import boxGetConfig from './getConfig.ts'

const jwtConfig = JwtConfig.fromConfigJsonString(boxGetConfig())
const jwtAuth = new BoxJwtAuth({ config: jwtConfig })
jwtAuth.asUser(user.boxAppUserId)
const boxClient = new BoxClient({ auth: jwtAuth })

const folderId = '200000000000' // fails with real folder ID, too
await boxClient.folders.getFolderItems(folderId)
```

The last line fails with the following error:

```
request to https://api.box.com/2.0/folders/200000000000/items failed, reason: Client network socket disconnected before secure TLS connection was established
```

I don't get this error locally (presumably because the request is made over HTTP), but the error shows up in production.

Downgrading to 0.1.7 fixed the issue.

### Versions Used

Typescript SDK: 0.1.8
Platform: Node.js (Vercel / AWS Lambda)
Node.js: 18.18.2

**Comment by mwwoda** [comment]
Hi @michaelhays 
Even locally the requests should be done via https. If this is only happening in an AWS Lambda / Vercel environment, could it be a configuration issue? Check your network, proxy or vpc configuration to make sure it's not interfering. Have you been able to reproduce this in another environment? It would be very helpful to determine the root cause if we could reproduce it on our side. 

I see that browser support was introduced in version 0.1.8, so there is a possibility that some of the changes made are not compatible with the environment you are trying to run it in.

**Comment by michaelhays** [comment]
Hey @mwwoda, thanks for the response. I'll debug a bit more and try it out in some different environments; should have some time to explore more thoroughly next week.

**Comment by michaelhays** [comment]
I upgraded to `box-typescript-sdk-gen` 0.2.0, and Node.js 20 on Vercel, and am no longer seeing this issue. Seems safe to close!
